local_name: TP
runmode: release             # 开发模式, debug, release, test
# addr: 39.99.53.8:2333
addr: 127.0.0.1:8080
port: :8080
db:  # DB 配置 部署时环境变量覆盖
  name: TP
  addr: 127.0.0.1:3306
  username: root
  password: 12345678